{"uuid": "b13754bb-c447-4cd3-a902-d2eaab408cdc", "children": ["a5aa298e-2e5c-4983-8946-1c0a3b3176a2"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ssh_ip'\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/ctpriv-scripts/altice/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/fixtures_4x.py\", line 47, in setup_profiles\n    instantiate_profile_obj = instantiate_profile(get_configuration['access_point'][0],\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 65, in __init__\n    self.ssh_ip = credentials['ssh_ip']\n"}, "start": 1696922277845, "stop": 1696922277845}], "start": 1696922277845, "stop": 1696922277861}