{"uuid": "eb0cadcd-299d-49a9-80b2-a30ed270c79d", "children": ["fb569f87-f03a-43fc-b518-6eb40743b591"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "AttributeError: 'AController' object has no attribute 'use_ssh'\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/ctpriv-scripts/altice/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/fixtures_4x.py\", line 47, in setup_profiles\n    instantiate_profile_obj = instantiate_profile(get_configuration['access_point'][0],\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 88, in __init__\n    if not (self.use_ssh) and self.mode:\n"}, "start": 1696930215867, "stop": 1696930215868}], "start": 1696930215867, "stop": 1696930215973}