{"uuid": "24ddc2fe-4fca-4ca8-b0a0-9b40cec44da0", "children": ["fd1d5f95-28e4-47bb-b84c-ef50b88741fd"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ssh_ip'\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/ctpriv-scripts/altice/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/fixtures_4x.py\", line 47, in setup_profiles\n    instantiate_profile_obj = instantiate_profile(get_configuration['access_point'][0],\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 65, in __init__\n    self.ssh_ip = credentials['ssh_ip']\n"}, "start": 1696922277817, "stop": 1696922277818}], "start": 1696922277817, "stop": 1696922277843}